#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl stop nmap-extended-daemon.service >/dev/null 2>&1 || true
    systemctl disable nmap-extended-daemon.service >/dev/null 2>&1 || true
fi

exit 0
